const Strings = {
  accountLabel: 'easypaisa Account',
  rewardText: 'My Rewards',
  balanceLabel: 'Available Balance',
  showBalanceText: text => `Rs. ${text}`,
  hiddenBalanceText: '* * * * * *',
  tapToShowBalance: 'Tap to show balance',
  tapToHideBalance: 'Tap to hide balance',
  account: 'ACCOUNT',
  location: 'Location',
  expandRadius: 'Expand Radius',
  sendMoney: 'Send Money',
  billPayment: 'Bill Payment',
  mobilePackages: 'Mobile Packages',
  help: 'Help',
  km: 'KM',
  city: 'IslamAbad',
  version: 'Version V',
  accordingBodyText:
    'Your first cash Deposit needs to be made through a Biometric (BVS) CashPoint',
  permissionDenied: 'Permission Denied',
  noDeviceFound: 'No device found',
  buttonText: {
    addCash: 'Add Cash',
    cashDeposit: 'Cash Deposit',
    cashPoints: 'Cash Points',
    cashPointsBVS: '(BVS) Cash Points',
    howToDepositCash: 'How to deposit Cash',
    manageCard: 'Manage card',
    edit: 'Edit',
    readMore: 'Read more',
    schedulePayments: 'Schedule Payments',
    getHelp: 'Get Help',
  },
  header: {
    title: {
      myAccountScreen: 'Account Settings',
      menuDrawerScreen: 'My Account',
      cashPointsScreen: 'Cash Deposit',
      promotionScreen: 'Promotions',
      cameraScreen: 'Camera',
    },
    subtitle: {
      myAccountScreen: 'Account info, Settings & More',
      menuDrawerScreen: 'Profile, Settings & More',
    },
  },
  menuOptions: {
    accountInformation: 'Account Information',
    linkTelenorBank: 'Link Telenor Microfinance Bank',
    linkDebitCard: 'Link Debit Card',
    GetTaxCertificate: 'Get Your Tax Certificate',
    openNewGenAccount: 'Open NewGenAccount',
    becomeRaastMerchant: 'Become a RAAST Merchant',
    accountLevel: 'Account Level',
    transactionHistory: 'Transaction History',
    openNewGenAccounts: 'Open NewGen Account',
    myAccount: 'My Account',
    goalsAndRewards: 'Goals & Rewards',
    myApprovals: 'My Approvals',
    taxCertificate: 'Tax Certificate',
    subscribedServices: 'Subscribed Services',
    securityPreferences: 'Security Preferences',
    customerSupport: 'Customer Support',
    feeDetails: 'Fee Details',
    helpFaqs: 'Help & FAQs',
  },
  carousalItems: {
    easyLoad: 'Easyload',
    easycash: 'Easycash',
    savingsPocket: 'Savings Pocket',
    inviteAndEarn: 'Invite & Earn',
    donations: 'Donations',
    termDeposit: 'Term Deposit',
    dailyRewards: 'Daily Rewards',
    buyNowPayLater: 'Buy Now Pay Later',
    insuranceMarketplace: 'Insurance Marketplace',
    mTag: 'M-Tag',
    rsOneGame: 'Rs.1 Game',
    raastPayment: 'Raast Payment',
    discounts: 'Discounts',
    miniApp: 'Mini App',
    topups: 'Topups',
    remittance: 'Remittance',
    education: 'Education',
    nadraFee: 'NADRA fee',
    onlinePayment: 'Online Payment',
    enterAndWin: 'Enter and Win',
    creditScore: 'Credit Score',
    tohfa: 'Tohfa',
    seeAll: 'See All',
  },
  sliderLabels: {
    km1: '1 KM',
    km10: '10 KM',
    km20: '20 KM',
  },
  badge: {
    new: 'NEW',
  },
  toggleSwitch: {
    english: 'Eng',
    urdu: 'اردو',
  },
  sectionTitle: {
    moreWithEasyPaisa: 'More with easypaisa',
    getDebitCard: 'Get your easypaisa Debit Card',
    discoverMiniApps: 'Discover miniApps on easypaisa',
    whatsNew: "Tap to see what's New",
    scheduleTransactions: 'Schedule Your Transactions',
  },
  debitCard: {
    onlineCardTitle: 'Online Card',
    onlineCardSubtitle: 'Only for Online Payments in Pakistan',
    plasticCardTitle: 'Plastic Card',
    plasticCardSubtitle: 'Use at any ATM or Shop in Pakistan',
  },
  CustomCard: {
    scheduleCard: {
      title: 'Set payments in advance',
      subtitle: 'Now Setup Mobile Packages and Easyload in advance.',
    },
    helpCard: {
      title: 'Help & Customer Support',
      subtitle:
        'Register a complaint or get quick help on queries related to easypaisa',
    },
  },
};

export default Strings;
